apiVersion: v1
kind: Pod
metadata:
  name: donkey-framework
spec:
  restartPolicy: OnFailure
  containers:
  - name: donkey
    image: mdlopezme/ucsdrobocar:staging
    securityContext:
      privileged: true
    # command: ["/bin/sleep", "3650d"]
    volumeMounts:
    - mountPath: /dev/bus/usb
      name: usb-bus
  volumes:
  - name: usb-bus
    hostPath:
      path: /dev/bus/usb